**Problem : 1**

**1. Initialize an empty array with size 2X2.**

In [ ]:
import numpy as np
np.empty([2,2])

array([[4.97304150e-310, 0.00000000e+000],
       [1.37962320e-306, 8.34449382e-308]])

 **2. Initialize an all one array with size 4X2.**

In [ ]:
import numpy as np
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

**3. Return a new array of given shape and type, filled with fill value.**

In [ ]:
import numpy as np
array = np.full(shape=(3,2), fill_value=5, dtype=int)
print(array)

[[5 5]
 [5 5]
 [5 5]]


**4. Return a new array of zeros with same shape and type as a given array.**

In [ ]:
import numpy as np
array = np.zeros(shape=(4,2), dtype=int)
print(array)


[[0 0]
 [0 0]
 [0 0]
 [0 0]]


**5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}**

In [ ]:
import numpy as np
new_array = np.ones(shape=(6,9), dtype=int)
print(new_array)

[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]


**6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}**

In [ ]:
import numpy as np
new_list = [1,2,3,4]
numpy_array=np.array(new_list)
print(numpy_array)

[1 2 3 4]


**Problem : 2**

**1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.**

In [ ]:
import numpy as np
array = np.arange(10, 50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}**

In [ ]:
import numpy as np
matrix = np.arange(9) .reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**3. Create a 3X3 identity matrix.{Hint:np.eye()}**

In [ ]:
import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}**

In [ ]:
import numpy as np
random_array = np.random.random(30)
mean_value = random_array.mean()
print(mean_value)

0.4920999892357526


**5. Create a 10X10 array with random values and find the minimum and maximum values.**

In [ ]:
import numpy as np
array = np.random.random((10, 10))
min_value = array.min()
max_value = array.max()
print(min_value)
print(max_value)

0.005850542065389708
0.9951048749807833


**6. Create a zero array of size 10 and replace 5th element with 1.**

In [ ]:
import numpy as np
array = np.zeros(10)
array[4]=1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**7. Reverse an array arr = [1,2,0,0,4,0].**

In [ ]:
import numpy as np
arr =np.array([1,2,0,0,4,0])
reversed_array = arr[::-1]
print(reversed_array)

[0 4 0 0 2 1]


**8. Create a 2d array with 1 on border and 0 inside.**

In [ ]:
import numpy as np
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**9. Create a 8X8 matrix and fill it with a checkerboard pattern.**

In [ ]:
import numpy as np
array = np.zeros((8, 8), dtype=int)
array[1::2, ::2] = 1
array[::2, 1::2] = 1
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Problem: 3**

**For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);**

**v = np.array([9,10]) and w = np.array([11,12]);**

**1. Add the two array.**

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
result = x + y
print(result)

[[ 6  8]
 [10 13]]


**2. Subtract the two array.**

In [25]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
result = x - y
result

array([[-4, -4],
       [-4, -3]])

**3. Multiply the array with any integers of your choice.**

In [28]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
result = x * 2
print(result)

[[ 2  4]
 [ 6 10]]


**4. Find the square of each element of the array.**

In [27]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
result = x ** 2
print(result)

[[ 1  4]
 [ 9 25]]


**5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.**

In [26]:
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)

print(f"Dot product of v and w: {dot_v_w}")
print(f"Dot product of x and v: {dot_x_v}")
print(f"Dot product of x and y: {dot_x_y}")

Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]


**6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.**

In [30]:
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

xy_row = np.vstack((x, y))

vw_col = np.hstack((v.reshape(-1, 1), w.reshape(-1, 1)))

print("Concatenation of x and y along rows:")
print(xy_row)

print("\nConcatenation of v and w along columns:")
print(vw_col)

Concatenation of x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
[[ 9 11]
 [10 12]]


**7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?**

In [31]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

try:
    result = np.concatenate((x, v), axis=1)
    print("Concatenation result:")
    print(result)
except ValueError as e:
    print("Error:", e)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


**Problem: 4**

**• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);**

**Prove following with Numpy:**
**1. Prove A.A−1 = I.**
**2. Prove AB ̸= BA.**
**3. Prove (AB)**

**T = BTAT
.**

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
identity_matrix = np.eye(2)
print("A * A^-1:")
print(result)
print("Is A * A^-1 approximately I?", np.allclose(result, identity_matrix))

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:")
print(AB)
print("BA:")
print(BA)
print("Is AB equal to BA?", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T A^T
AB_transpose = np.transpose(np.dot(A, B))
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T:")
print(AB_transpose)
print("B^T A^T:")
print(BT_AT)
print("Is (AB)^T equal to B^T A^T?", np.array_equal(AB_transpose, BT_AT))


A * A^-1:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is A * A^-1 approximately I? True
AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
Is AB equal to BA? False
(AB)^T:
[[23 51]
 [13 29]]
B^T A^T:
[[23 51]
 [13 29]]
Is (AB)^T equal to B^T A^T? True


**• Solve the following system of Linear equation using Inverse Methods.**

**2x − 3y + z = −1**

**x − y + 2z = −3**

**3x + y − z = 9**
**{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}**

In [ ]:
import numpy as np

A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution (X):")
print(X)


Solution (X):
[ 2.  1. -2.]


**• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}**

In [33]:
import numpy as np

A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
X_inv = np.dot(A_inv, B)

X_solve = np.linalg.solve(A, B)

det_A = np.linalg.det(A)

eigenvalues, eigenvectors = np.linalg.eig(A)

norm_B = np.linalg.norm(B)

print("Solution using np.linalg.inv():")
print(X_inv)

print("\nSolution using np.linalg.solve():")
print(X_solve)

print("\nDeterminant of A:")
print(det_A)

print("\nEigenvalues of A:")
print(eigenvalues)

print("\nEigenvectors of A:")
print(eigenvectors)

print("\nNorm of B:")
print(norm_B)


Solution using np.linalg.inv():
[ 2.  1. -2.]

Solution using np.linalg.solve():
[ 2.  1. -2.]

Determinant of A:
-19.000000000000004

Eigenvalues of A:
[ 1.6420583+1.75757401j  1.6420583-1.75757401j -3.2841166+0.j        ]

Eigenvectors of A:
[[-0.382981  -0.42412518j -0.382981  +0.42412518j -0.42095922+0.j        ]
 [-0.50252881+0.17376846j -0.50252881-0.17376846j -0.48621189+0.j        ]
 [-0.62507016+0.j         -0.62507016-0.j          0.76576193+0.j        ]]

Norm of B:
9.539392014169456
